-- Laundry tracker schema, access controls, seed data, and Realtime setup.
-- Safe to paste into the Supabase SQL Editor as one script.

begin;

create table if not exists public.machines (
  id text primary key,
  type text not null check (type in ('washer', 'dryer')),
  status text not null default 'free' check (status in ('free', 'in_use')),
  in_use_since timestamp with time zone null,
  qr_token text unique not null,
  created_at timestamp with time zone not null default now(),
  constraint machines_id_format_check check (
    id ~ '^(washer|dryer)_[1-9][0-9]*$'
  ),
  constraint machines_type_matches_id_check check (
    split_part(id, '_', 1) = type
  ),
  constraint machines_status_timestamp_check check (
    (status = 'free' and in_use_since is null)
    or status = 'in_use'
  )
);

create table if not exists public.machine_history (
  id bigint generated by default as identity primary key,
  machine_id text not null references public.machines(id),
  status text not null check (status in ('free', 'in_use')),
  timestamp timestamp with time zone not null default now()
);

create index if not exists machines_type_status_idx
  on public.machines (type, status);

create index if not exists machine_history_machine_timestamp_idx
  on public.machine_history (machine_id, timestamp desc);

-- Explicit grants are required for projects that do not auto-expose new
-- public tables to the Data API. Public clients may read status fields only;
-- qr_token remains unavailable to the browser.
revoke all on table public.machines from anon, authenticated;
grant select (id, type, status, in_use_since, created_at)
  on table public.machines to anon, authenticated;

revoke all on table public.machine_history from anon, authenticated;
revoke all on sequence public.machine_history_id_seq from anon, authenticated;

-- Edge Functions using a server-side service-role key can manage both tables.
grant all on table public.machines, public.machine_history to service_role;
grant usage, select on sequence public.machine_history_id_seq to service_role;

alter table public.machines enable row level security;
alter table public.machine_history enable row level security;

drop policy if exists "Public can read machine availability" on public.machines;
create policy "Public can read machine availability"
  on public.machines
  for select
  to anon, authenticated
  using (true);

-- machine_history intentionally has no public policies. It is reserved for
-- trusted Edge Functions and future analytics.

insert into public.machines (id, type, status, in_use_since, qr_token)
select
  'washer_' || machine_number,
  'washer',
  'free',
  null,
  gen_random_uuid()::text
from generate_series(1, 41) as machine_number
on conflict (id) do nothing;

insert into public.machines (id, type, status, in_use_since, qr_token)
select
  'dryer_' || machine_number,
  'dryer',
  'free',
  null,
  gen_random_uuid()::text
from generate_series(1, 32) as machine_number
on conflict (id) do nothing;

-- Add machines to the existing Supabase Realtime publication without touching
-- objects inside the protected realtime schema.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'machines'
  ) then
    alter publication supabase_realtime add table public.machines;
  end if;
end
$$;

commit;
